/*! Generated by Font Squirrel (https://www.fontsquirrel.com) on November 2, 2017 */



@font-face {
    font-family: 'proxima_novabold';
    src: url('../fonts/mark_simonson_-_proxima_nova_bold.woff2') format('woff2'),
         url('../fonts/mark_simonson_-_proxima_nova_bold.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}




@font-face {
    font-family: 'proxima_novalight';
    src: url('../fonts/mark_simonson_-_proxima_nova_light.woff2') format('woff2'),
         url('../fonts/mark_simonson_-_proxima_nova_light.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}




@font-face {
    font-family: 'proxima_novasemibold';
    src: url('../fonts/mark_simonson_-_proxima_nova_semibold.woff2') format('woff2'),
         url('../fonts/mark_simonson_-_proxima_nova_semibold.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}




@font-face {
    font-family: 'proxima_novaregular';
    src: url('../fonts/mark_simonson_-_proxima_nova.woff2') format('woff2'),
         url('../fonts/mark_simonson_-_proxima_nova.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}




@font-face {
    font-family: 'robotobold';
    src: url('../fonts/roboto-bold.woff2') format('woff2'),
         url('../fonts/roboto-bold.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}

@font-face {
    font-family: 'fjallaoneregular';
    src: url('../fonts/fjallaone-regular.woff2') format('woff2'),
         url('../fonts/fjallaone-regular.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}
